# syntax=docker/dockerfile:1.2.1

FROM ghcr.io/tianocore/containers/ubuntu-22-build:46802aa as builder
RUN git clone https://github.com/tianocore/edk2.git && \
    git -C edk2 checkout edk2-stable202311 && \
    git -C edk2 submodule update --init --recursive
RUN make -j$(cat /proc/cpuinfo  | grep processor | wc -l) -C /edk2/BaseTools/Source/C
SHELL ["/bin/bash", "-c"]

FROM builder as build-debug-x64
RUN --mount=type=bind,target=/edk2/cyanfs,rw \
    cd /edk2 && source edksetup.sh && \
    build -p cyanfs/uefi/Cyanfs.dsc -t GCC5 -a X64 -b DEBUG

FROM builder as build-debug-aarch64
RUN --mount=type=bind,target=/edk2/cyanfs,rw \
    cd /edk2 && source edksetup.sh && \
    build -p cyanfs/uefi/Cyanfs.dsc -t GCC5 -a AARCH64 -b DEBUG

FROM builder as build-release-x64
RUN --mount=type=bind,target=/edk2/cyanfs,rw \
    cd /edk2 && source edksetup.sh && \
    build -p cyanfs/uefi/Cyanfs.dsc -t GCC5 -a X64 -b RELEASE

FROM builder as build-release-aarch64
RUN --mount=type=bind,target=/edk2/cyanfs,rw \
    cd /edk2 && source edksetup.sh && \
    build -p cyanfs/uefi/Cyanfs.dsc -t GCC5 -a AARCH64 -b RELEASE

FROM scratch as package
COPY --from=build-debug-x64 /edk2/Build/Cyanfs /
COPY --from=build-debug-aarch64 /edk2/Build/Cyanfs /
COPY --from=build-release-x64 /edk2/Build/Cyanfs /
COPY --from=build-release-aarch64 /edk2/Build/Cyanfs /
